"""update financial goals model

Revision ID: 51c8591a962e
Revises: bc960b6892ea
Create Date: 2024-05-02 05:40:31.200158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51c8591a962e'
down_revision = 'bc960b6892ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_goals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('created_by', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('created_on', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('start_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('end_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('current_amount', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('category', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=128), nullable=True))
        batch_op.drop_column('deadline')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_goals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deadline', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.drop_column('status')
        batch_op.drop_column('category')
        batch_op.drop_column('current_amount')
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')
        batch_op.drop_column('created_on')
        batch_op.drop_column('created_by')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
